# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\006simple',
  serialized_pb=b'\n\x0csimple.proto\"A\n\x06Simple\x12\x11\n\tfloatval1\x18\x01 \x01(\x02\x12\x11\n\tfloatval2\x18\x02 \x01(\x02\x12\x11\n\tfloatval3\x18\x03 \x01(\x02\x42\x08Z\x06simpleb\x06proto3'
)




_SIMPLE = _descriptor.Descriptor(
  name='Simple',
  full_name='Simple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='floatval1', full_name='Simple.floatval1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='floatval2', full_name='Simple.floatval2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='floatval3', full_name='Simple.floatval3', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['Simple'] = _SIMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Simple = _reflection.GeneratedProtocolMessageType('Simple', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLE,
  '__module__' : 'simple_pb2'
  # @@protoc_insertion_point(class_scope:Simple)
  })
_sym_db.RegisterMessage(Simple)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
